// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudioB2B.Infrastructure.Persistence.Tenant;

#nullable disable

namespace StudioB2B.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260313100000_AddModulesAndExpandManufacturer")]
    partial class AddModulesAndExpandManufacturer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
