// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudioB2B.Infrastructure.Persistence.Tenant;

#nullable disable

namespace StudioB2B.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260328120000_AddPaymentRateDurationTiers")]
    partial class AddPaymentRateDurationTiers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Full model snapshot is maintained in TenantDbContextModelSnapshot.cs
        }
    }
}
