// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioB2B.Infrastructure.Persistence.Tenant;

#nullable disable

namespace StudioB2B.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260226153551_new role")]
    partial class newrole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ClientTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ModeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OGRN")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("longtext");

                    b.Property<string>("OzonName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("ModeId");

                    b.ToTable("MarketplaceClients");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient1CSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OGRN")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("longtext");

                    b.Property<string>("OzonName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId")
                        .IsUnique();

                    b.ToTable("MarketplaceClient1CSettings");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClientMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceClientModes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClientSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId");

                    b.ToTable("MarketplaceClientSettings");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClientType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceClientTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.TenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TenantRoleTenantUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("char(36)");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TenantRoleTenantUser");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClientType", "ClientType")
                        .WithMany()
                        .HasForeignKey("ClientTypeId");

                    b.HasOne("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClientMode", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeId");

                    b.Navigation("ClientType");

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient1CSettings", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient", "MarketplaceClient")
                        .WithOne("Settings1C")
                        .HasForeignKey("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient1CSettings", "MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClientSettings", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient", "MarketplaceClient")
                        .WithMany("Settings")
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("TenantRoleTenantUser", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Tenant.TenantRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Tenant.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenant.Marketplace.MarketplaceClient", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Settings1C");
                });
#pragma warning restore 612, 618
        }
    }
}
