// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioB2B.Infrastructure.Persistence.Tenant;

#nullable disable

namespace StudioB2B.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260417204843_AddCommunicationOutgoingMessages")]
    partial class AddCommunicationOutgoingMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudioB2B.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apartment")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("House")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.AppFunction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PageId");

                    b.ToTable("Functions", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.BlockedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("BlockedEntities", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CalculationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResultKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CalculationRules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationOutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SentByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SentByUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentByUserId");

                    b.ToTable("CommunicationOutgoingMessages");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationPaymentRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TaskType")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TaskType", "IsActive");

                    b.ToTable("CommunicationPaymentRates", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChatType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ExternalStatus")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviewText")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TotalTimeSpentTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WasPreviouslyCompleted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MarketplaceClientId");

                    b.HasIndex("Status");

                    b.HasIndex("TaskType", "ExternalId", "MarketplaceClientId")
                        .IsUnique();

                    b.ToTable("CommunicationTasks", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTaskLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunicationTaskLogs", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunicationTimeEntries", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.DateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DateTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.DeliveryMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DeliveryTypeId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTypeId");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.DeliveryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.FieldAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("FieldAuditLogs", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Contact")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Domain")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("ExistId")
                        .HasColumnType("int");

                    b.Property<string>("ExistName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MarketPrefix")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("TecdocSupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("Manufacturers", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ClientTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ModeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ModeId2")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OGRN")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("longtext");

                    b.Property<string>("OzonName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("ModeId");

                    b.HasIndex("ModeId2");

                    b.ToTable("MarketplaceClients");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClient1CSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OGRN")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("longtext");

                    b.Property<string>("OzonName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId")
                        .IsUnique();

                    b.ToTable("MarketplaceClient1CSettings");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClientMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceClientModes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClientSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId");

                    b.ToTable("MarketplaceClientSettings");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClientType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceClientTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("OzonOrderId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProductInfoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SystemStatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WarehouseInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("WarehouseInfoId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PriceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PriceTypeId");

                    b.ToTable("OrderPrices");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderProductInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OrderProductInfos");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CancelledWithCompensationMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("ClearingId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Commission")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CommissionPercent")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTime?>("CompensationStatusChangeMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CompensationStatusDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("CompensationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuperEconom")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LogisticBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OfferId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long?>("OzonOrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OzonReturnId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlaceAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PlaceName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PostingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProductName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("ProductPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProductPriceCurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("ProductPriceWithoutCommission")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<long?>("ProductSku")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReturnClearingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReturnReasonName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Schema")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StorageArrivedMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StorageCurrencyCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long?>("StorageDays")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("StorageSum")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("StorageTariffStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TechnicalReturnMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UtilizationForecastDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("UtilizationSum")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("VisualStatusChangeMoment")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VisualStatusDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("VisualStatusId")
                        .HasColumnType("int");

                    b.Property<string>("VisualStatusSysName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OzonOrderId");

                    b.HasIndex("OzonReturnId")
                        .IsUnique();

                    b.HasIndex("PostingNumber");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("VisualStatusSysName");

                    b.ToTable("OrderReturns", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MarketplaceClientTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Synonym")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientTypeId");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FromSystemStatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ToSystemStatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FromSystemStatusId");

                    b.HasIndex("ToSystemStatusId");

                    b.ToTable("OrderTransactions", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransactionFieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FixedValue")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("ValueSource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderTransactionId");

                    b.ToTable("OrderTransactionFieldRules", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("FieldsUpdated")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PerformedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("PricesUpdated")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("OrderTransactionId");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("OrderId", "OrderTransactionId");

                    b.ToTable("OrderTransactionHistories", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransactionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("FixedValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Formula")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PriceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("ValueSource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderTransactionId");

                    b.HasIndex("PriceTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderTransactionRules", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OzonPushNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PostingNumber")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId");

                    b.HasIndex("MessageType");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("SellerId");

                    b.ToTable("OzonPushNotifications", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PageColumn", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PageId");

                    b.ToTable("PageColumns", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFullAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PermissionFunction", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("FunctionId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("PermissionFunctions", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PermissionPage", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "PageId");

                    b.HasIndex("PageId");

                    b.ToTable("PermissionPages", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PermissionPageColumn", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PageColumnId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "PageColumnId");

                    b.HasIndex("PageColumnId");

                    b.ToTable("PermissionPageColumns", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PriceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CalculationRule")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliveryScheme")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUserDefined")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PriceTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Article")
                        .HasColumnType("longtext");

                    b.Property<string>("Barcode")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("Sku")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId", "AttributeId")
                        .IsUnique();

                    b.ToTable("ProductAttributeValues", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeliveryMethodId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasReturn")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("InProcessAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PostingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("MarketplaceClientId");

                    b.HasIndex("PostingNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.ShipmentDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DateTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Value")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DateTypeId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentDates");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.StatusColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderStatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("StatusColors");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.SyncJobHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HangfireJobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InitiatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResultJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HangfireJobId");

                    b.ToTable("SyncJobHistories", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.SyncJobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CronDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HangfireRecurringJobId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("SyncParams")
                        .HasColumnType("json");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HangfireRecurringJobId")
                        .IsUnique()
                        .HasFilter("HangfireRecurringJobId IS NOT NULL");

                    b.ToTable("SyncJobSchedules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantLoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginCodes", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TenantModules", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantUserActivationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserActivationTokens", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantUserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long?>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Settings1C")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.WarehouseInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RecipientWarehouseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SenderWarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientWarehouseId");

                    b.HasIndex("SenderWarehouseId");

                    b.ToTable("WarehouseInfos", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.WarehouseStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("WarehouseStocks", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.AppFunction", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Page", "Page")
                        .WithMany("Functions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.BlockedEntity", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Permission", "Permission")
                        .WithMany("BlockedEntities")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Category", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationOutgoingMessage", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SentByUser");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationPaymentRate", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTask", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClient", "MarketplaceClient")
                        .WithMany()
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTaskLog", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.CommunicationTask", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTimeEntry", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.CommunicationTask", "Task")
                        .WithMany("TimeEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.DeliveryMethod", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.DeliveryType", "DeliveryType")
                        .WithMany()
                        .HasForeignKey("DeliveryTypeId");

                    b.Navigation("DeliveryType");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClient", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClientType", "ClientType")
                        .WithMany()
                        .HasForeignKey("ClientTypeId");

                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClientMode", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeId");

                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClientMode", "Mode2")
                        .WithMany()
                        .HasForeignKey("ModeId2");

                    b.Navigation("ClientType");

                    b.Navigation("Mode");

                    b.Navigation("Mode2");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClient1CSettings", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClient", "MarketplaceClient")
                        .WithOne("Settings1C")
                        .HasForeignKey("StudioB2B.Domain.Entities.MarketplaceClient1CSettings", "MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClientSettings", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClient", "MarketplaceClient")
                        .WithMany("Settings")
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderEntity", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Orders")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.OrderStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.WarehouseInfo", "WarehouseInfo")
                        .WithMany()
                        .HasForeignKey("WarehouseInfoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipient");

                    b.Navigation("Shipment");

                    b.Navigation("Status");

                    b.Navigation("SystemStatus");

                    b.Navigation("WarehouseInfo");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderPrice", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("StudioB2B.Domain.Entities.OrderEntity", "OrderEntity")
                        .WithMany("Prices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId");

                    b.Navigation("Currency");

                    b.Navigation("OrderEntity");

                    b.Navigation("PriceType");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderProductInfo", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.OrderEntity", "OrderEntity")
                        .WithOne("ProductInfo")
                        .HasForeignKey("StudioB2B.Domain.Entities.OrderProductInfo", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("StudioB2B.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("OrderEntity");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderReturn", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.OrderEntity", "Order")
                        .WithMany("Returns")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Returns")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderStatus", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClientType", "MarketplaceClientType")
                        .WithMany()
                        .HasForeignKey("MarketplaceClientTypeId");

                    b.Navigation("MarketplaceClientType");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransaction", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.OrderStatus", "FromSystemStatus")
                        .WithMany()
                        .HasForeignKey("FromSystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.OrderStatus", "ToSystemStatus")
                        .WithMany()
                        .HasForeignKey("ToSystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromSystemStatus");

                    b.Navigation("ToSystemStatus");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransactionFieldRule", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.OrderTransaction", "OrderTransaction")
                        .WithMany("FieldRules")
                        .HasForeignKey("OrderTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderTransaction");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransactionHistory", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.OrderTransaction", "OrderTransaction")
                        .WithMany()
                        .HasForeignKey("OrderTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("OrderTransaction");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransactionRule", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.OrderTransaction", "OrderTransaction")
                        .WithMany("Rules")
                        .HasForeignKey("OrderTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("OrderTransaction");

                    b.Navigation("PriceType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OzonPushNotification", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClient", "MarketplaceClient")
                        .WithMany()
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PageColumn", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Page", "Page")
                        .WithMany("Columns")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PermissionFunction", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.AppFunction", "Function")
                        .WithMany("PermissionFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Permission", "Permission")
                        .WithMany("Functions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PermissionPage", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Page", "Page")
                        .WithMany("PermissionPages")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Permission", "Permission")
                        .WithMany("Pages")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PermissionPageColumn", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.PageColumn", "PageColumn")
                        .WithMany("PermissionPageColumns")
                        .HasForeignKey("PageColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Permission", "Permission")
                        .WithMany("PageColumns")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageColumn");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Product", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("StudioB2B.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.ProductAttributeValue", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.ProductAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Recipient", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.MarketplaceClient", "MarketplaceClient")
                        .WithMany()
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeliveryMethod");

                    b.Navigation("MarketplaceClient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.ShipmentDate", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.DateType", "DateType")
                        .WithMany()
                        .HasForeignKey("DateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Dates")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateType");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.StatusColor", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Colors")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantLoginCode", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantUserActivationToken", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantUserPermission", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.TenantUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.WarehouseInfo", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Warehouse", "RecipientWarehouse")
                        .WithMany()
                        .HasForeignKey("RecipientWarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Warehouse", "SenderWarehouse")
                        .WithMany()
                        .HasForeignKey("SenderWarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecipientWarehouse");

                    b.Navigation("SenderWarehouse");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.WarehouseStock", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.AppFunction", b =>
                {
                    b.Navigation("PermissionFunctions");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.CommunicationTask", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.MarketplaceClient", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Settings1C");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderEntity", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ProductInfo");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.OrderTransaction", b =>
                {
                    b.Navigation("FieldRules");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Page", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Functions");

                    b.Navigation("PermissionPages");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.PageColumn", b =>
                {
                    b.Navigation("PermissionPageColumns");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Permission", b =>
                {
                    b.Navigation("BlockedEntities");

                    b.Navigation("Functions");

                    b.Navigation("PageColumns");

                    b.Navigation("Pages");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Product", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Orders");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.TenantUser", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
