// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioB2B.Infrastructure.Persistence.Tenant;

#nullable disable

namespace StudioB2B.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260306170000_AddIsRequiredToOrderTransactionFieldRules")]
    partial class AddIsRequiredToOrderTransactionFieldRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransactionFieldRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EntityPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OrderTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FixedValue")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("ValueSource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderTransactionId");

                    b.ToTable("OrderTransactionFieldRules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransactionFieldRule", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderTransaction", "OrderTransaction")
                        .WithMany("FieldRules")
                        .HasForeignKey("OrderTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
