// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioB2B.Infrastructure.Persistence.Tenant;

#nullable disable

namespace StudioB2B.Infrastructure.Persistence.Tenant.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudioB2B.Domain.Entities.Common.FieldAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ChangedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("FieldAuditLogs", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ClientTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Company")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ModeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OGRN")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("longtext");

                    b.Property<string>("OzonName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("ModeId");

                    b.ToTable("MarketplaceClients");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient1CSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("INN")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OGRN")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipForm")
                        .HasColumnType("longtext");

                    b.Property<string>("OzonName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId")
                        .IsUnique();

                    b.ToTable("MarketplaceClient1CSettings");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceClientModes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientId");

                    b.ToTable("MarketplaceClientSettings");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MarketplaceClientTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apartment")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<string>("House")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.CalculationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResultKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CalculationRules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.DateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DateTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.DeliveryMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DeliveryTypeId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTypeId");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.DeliveryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("OzonOrderId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProductInfoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecipientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SystemStatusId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("WarehouseInfoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("SystemStatusId");

                    b.HasIndex("WarehouseInfoId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PriceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PriceTypeId");

                    b.ToTable("OrderPrices");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderProductInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OrderProductInfos");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MarketplaceClientTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Synonym")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceClientTypeId");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FromSystemStatusId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ToSystemStatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FromSystemStatusId");

                    b.HasIndex("ToSystemStatusId");

                    b.ToTable("OrderTransactions", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransactionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OrderTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PerformedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("PricesUpdated")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("OrderTransactionId");

                    b.HasIndex("PerformedAtUtc");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("OrderId", "OrderTransactionId");

                    b.ToTable("OrderTransactionHistories", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransactionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("FixedValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Formula")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PriceTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("ValueSource")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderTransactionId");

                    b.HasIndex("PriceTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderTransactionRules", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeliveryMethodId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("InProcessAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MarketplaceClientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PostingNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryMethodId");

                    b.HasIndex("MarketplaceClientId");

                    b.HasIndex("PostingNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.ShipmentDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DateTypeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Value")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DateTypeId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentDates");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.StatusColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderStatusId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("StatusColors");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.SyncJobHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HangfireJobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InitiatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResultJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HangfireJobId");

                    b.ToTable("SyncJobHistories", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.SyncJobSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CronDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HangfireRecurringJobId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("SyncParams")
                        .HasColumnType("json");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HangfireRecurringJobId")
                        .IsUnique()
                        .HasFilter("HangfireRecurringJobId IS NOT NULL");

                    b.ToTable("SyncJobSchedules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.WarehouseInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RecipientWarehouseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SenderWarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientWarehouseId");

                    b.HasIndex("SenderWarehouseId");

                    b.ToTable("WarehouseInfos", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Article")
                        .HasColumnType("longtext");

                    b.Property<string>("Barcode")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("Sku")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.ProductAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.ProductAttributeValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId", "AttributeId")
                        .IsUnique();

                    b.ToTable("ProductAttributeValues", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.References.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.References.PriceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CalculationRule")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliveryScheme")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUserDefined")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PriceTypes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenants.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenants.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenants.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long?>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Settings1C")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Warehouses.WarehouseStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("WarehouseStocks", (string)null);
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientType", "ClientType")
                        .WithMany()
                        .HasForeignKey("ClientTypeId");

                    b.HasOne("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientMode", "Mode")
                        .WithMany()
                        .HasForeignKey("ModeId");

                    b.Navigation("ClientType");

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient1CSettings", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient", "MarketplaceClient")
                        .WithOne("Settings1C")
                        .HasForeignKey("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient1CSettings", "MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientSettings", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient", "MarketplaceClient")
                        .WithMany("Settings")
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceClient");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.DeliveryMethod", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.DeliveryType", "DeliveryType")
                        .WithMany()
                        .HasForeignKey("DeliveryTypeId");

                    b.Navigation("DeliveryType");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Order", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.Recipient", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Orders.Shipment", "Shipment")
                        .WithMany("Orders")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderStatus", "SystemStatus")
                        .WithMany()
                        .HasForeignKey("SystemStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Orders.WarehouseInfo", "WarehouseInfo")
                        .WithMany()
                        .HasForeignKey("WarehouseInfoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Recipient");

                    b.Navigation("Shipment");

                    b.Navigation("Status");

                    b.Navigation("SystemStatus");

                    b.Navigation("WarehouseInfo");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderPrice", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.References.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("StudioB2B.Domain.Entities.Orders.Order", "Order")
                        .WithMany("Prices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.References.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId");

                    b.Navigation("Currency");

                    b.Navigation("Order");

                    b.Navigation("PriceType");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderProductInfo", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.Order", "Order")
                        .WithOne("ProductInfo")
                        .HasForeignKey("StudioB2B.Domain.Entities.Orders.OrderProductInfo", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("StudioB2B.Domain.Entities.Products.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderStatus", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Marketplace.MarketplaceClientType", "MarketplaceClientType")
                        .WithMany()
                        .HasForeignKey("MarketplaceClientTypeId");

                    b.Navigation("MarketplaceClientType");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransaction", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderStatus", "FromSystemStatus")
                        .WithMany()
                        .HasForeignKey("FromSystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderStatus", "ToSystemStatus")
                        .WithMany()
                        .HasForeignKey("ToSystemStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromSystemStatus");

                    b.Navigation("ToSystemStatus");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransactionHistory", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderTransaction", "OrderTransaction")
                        .WithMany()
                        .HasForeignKey("OrderTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Tenants.User", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("OrderTransaction");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransactionRule", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.References.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderTransaction", "OrderTransaction")
                        .WithMany("Rules")
                        .HasForeignKey("OrderTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.References.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("OrderTransaction");

                    b.Navigation("PriceType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Recipient", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Shipment", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.DeliveryMethod", "DeliveryMethod")
                        .WithMany()
                        .HasForeignKey("DeliveryMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient", "MarketplaceClient")
                        .WithMany()
                        .HasForeignKey("MarketplaceClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeliveryMethod");

                    b.Navigation("MarketplaceClient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.ShipmentDate", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.DateType", "DateType")
                        .WithMany()
                        .HasForeignKey("DateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Orders.Shipment", "Shipment")
                        .WithMany("Dates")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateType");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.StatusColor", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Orders.OrderStatus", "OrderStatus")
                        .WithMany("Colors")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.WarehouseInfo", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Warehouses.Warehouse", "RecipientWarehouse")
                        .WithMany()
                        .HasForeignKey("RecipientWarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudioB2B.Domain.Entities.Warehouses.Warehouse", "SenderWarehouse")
                        .WithMany()
                        .HasForeignKey("SenderWarehouseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecipientWarehouse");

                    b.Navigation("SenderWarehouse");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Category", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Products.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Products.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("StudioB2B.Domain.Entities.Products.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Category");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.ProductAttributeValue", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Products.ProductAttribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Products.Product", "Product")
                        .WithMany("Attributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenants.UserRole", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Tenants.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Tenants.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Warehouses.WarehouseStock", b =>
                {
                    b.HasOne("StudioB2B.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioB2B.Domain.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany("Stocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Marketplace.MarketplaceClient", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Settings1C");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Order", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("ProductInfo");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderStatus", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.OrderTransaction", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Orders.Shipment", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Products.Product", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenants.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Tenants.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("StudioB2B.Domain.Entities.Warehouses.Warehouse", b =>
                {
                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
