services:
  studiob2b:
    image: bondarevevgeni/studio2b2:latest
    container_name: studiob2b
    ports:
      - "5184:5184"
    environment:
      - ConnectionStrings__MasterDb=Server=172.28.0.10;Port=3306;Database=StudioB2B_Master;User=root;Password=root;Allow User Variables=true;MaximumPoolSize=50;ConnectionI>
      - MultiTenancy__TenantDbConnectionTemplate=Server=172.28.0.10;Port=3306;Database=StudioB2B_Tenant_{0};User=root;Password=root;Allow User Variables=true;MaximumPoolSi>
      - ASPNETCORE_ENVIRONMENT=Production
      - MultiTenancy__MasterDomain=studiob2b.ru
      - Jwt__Secret=2B5F9B6E75C256999B7359FE076156E5
      - Backup__Endpoint=minio:9000
      - Backup__PublicEndpoint=minio.studiob2b.ru
      - Backup__Bucket=backups
      - Backup__AccessKey=minioadmin
      - Backup__SecretKey=minioadmin
      - Backup__UseSSL=false
      - Backup__DefaultRetentionDays=30
    volumes:
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    networks:
      - studiob2b_network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    networks:
      studiob2b_network:
        ipv4_address: 172.28.0.10
    ports:
      - "3306:3306"
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - studiob2b_network
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

networks:
  studiob2b_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  minio_data:

